# Generated by Django 5.1.1 on 2024-09-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_order_is_approved_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='rent_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='total_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
