# Generated by Django 5.0.1 on 2025-02-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_lease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='lease_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='lease_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='no_of_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='is_lease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='lease_terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
