# Generated by Django 5.0.1 on 2025-02-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bill_is_lease_bill_lease_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_months',
            field=models.IntegerField(default=0),
        ),
    ]
