# Generated by Django 4.0 on 2024-09-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarBodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(default='', max_length=30)),
                ('car_desc', models.CharField(default='', max_length=300)),
                ('year', models.IntegerField()),
                ('available', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='car/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.brand')),
                ('car_color', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.carcolor')),
                ('car_fuel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.carfuel')),
                ('car_model', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.carmodel')),
                ('transmission', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.cartransmission')),
            ],
        ),
    ]
