# Generated by Django 5.0.1 on 2024-10-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_car_insurance_file_car_insurance_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
