# Generated by Django 5.0.1 on 2024-10-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_carmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='price',
        ),
    ]
