# Generated by Django 5.0.1 on 2024-10-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_carmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
