# Generated by Django 5.0.1 on 2025-01-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_carmodel_price_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='myapp.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='myapp.car')),
            ],
        ),
    ]
