# Generated by Django 5.0.1 on 2025-02-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_carlocation_cartracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_360',
            field=models.ImageField(blank=True, help_text='Upload a 360-degree equirectangular image', null=True, upload_to='car/images_360'),
        ),
    ]
