# Generated by Django 5.0.1 on 2025-02-06 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_car_image_360'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.FloatField()),
                ('maintenance_history', models.CharField(max_length=20)),
                ('transmission_type', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
                ('battery_status', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('owner_type', models.CharField(max_length=20)),
                ('tire_condition', models.CharField(max_length=20)),
                ('brake_condition', models.CharField(max_length=20)),
                ('odometer_reading', models.FloatField()),
                ('insurance_premium', models.FloatField()),
                ('days_since_last_service', models.IntegerField()),
                ('prediction_result', models.BooleanField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.car')),
            ],
        ),
    ]
