# Generated by Django 5.0.1 on 2025-02-11 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_prediction_date_maintenanceprediction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceprediction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='maintenanceprediction',
            name='days_since_last_service',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='maintenanceprediction',
            name='engine_size',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='maintenanceprediction',
            name='mileage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='maintenanceprediction',
            name='odometer_reading',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='maintenanceprediction',
            name='service_history',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
