# Generated by Django 5.0.1 on 2025-02-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available_for_lease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='lease_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='maximum_lease_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='car',
            name='minimum_lease_months',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
