# Generated by Django 5.0.1 on 2024-09-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='driving_licence',
            field=models.ImageField(default='', upload_to='user/driving_licene'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='', upload_to='user/images'),
        ),
    ]
